'use client';

import Link from 'next/link';
import type { ReportQuotationRecord } from '@/types';
import Button from '@/components/ui/Button';
import { formatCurrency, formatDate } from '@/lib/utils';
import { Eye } from 'lucide-react';

function userLabel(row: ReportQuotationRecord): string {
  if (row.userName?.trim()) return row.userName.trim();
  return row.userEmail;
}

interface QuotationHistoryTableProps {
  quotations: ReportQuotationRecord[];
  loading?: boolean;
}

export default function QuotationHistoryTable({
  quotations,
  loading = false,
}: QuotationHistoryTableProps) {
  if (loading) {
    return (
      <p className="px-4 py-12 text-sm text-[#555555] text-center">Loading quotation history…</p>
    );
  }

  if (quotations.length === 0) {
    return (
      <p className="px-4 py-12 text-sm text-[#555555] text-center">
        No quotations found.
      </p>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm min-w-[800px]">
        <thead>
          <tr className="border-b border-[#c3c3c3] bg-[#f2f6ef]">
            {[
              'Quotation',
              'Client',
              'Product',
              'Pack',
              'Total',
              'Generated by',
              'Date',
              'Actions',
            ].map((h) => (
              <th
                key={h}
                className="px-4 py-3 text-left text-[12px] font-semibold text-[#555555] uppercase tracking-wide whitespace-nowrap"
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {quotations.map((q, i) => (
            <tr
              key={q.id}
              className={`border-b border-[#e8ece5] ${i % 2 === 0 ? 'bg-white' : 'bg-[#f2f6ef]/60'} hover:bg-[#f2f6ef]`}
            >
              <td className="px-4 py-3 font-mono text-xs text-[#314f2d] font-medium whitespace-nowrap">
                {q.quotationNumber}
              </td>
              <td className="px-4 py-3 font-medium text-[#0a0a0a] whitespace-nowrap">
                {q.clientName}
              </td>
              <td className="px-4 py-3 text-[#373737] max-w-[180px] truncate">
                {q.productName}
              </td>
              <td className="px-4 py-3 text-[#555555] tabular-nums whitespace-nowrap">
                {q.packWeightG}g
              </td>
              <td className="px-4 py-3 font-mono text-[#0a0a0a] whitespace-nowrap">
                {formatCurrency(q.totalPrice)}
              </td>
              <td className="px-4 py-3 text-[#373737]">
                <p className="font-medium text-[#0a0a0a] truncate max-w-[140px]">
                  {userLabel(q)}
                </p>
                {q.userName ? (
                  <p className="text-[11px] text-[#a3a29e] truncate max-w-[140px]">
                    {q.userEmail}
                  </p>
                ) : null}
              </td>
              <td className="px-4 py-3 text-[#555555] whitespace-nowrap">
                {formatDate(q.createdAt)}
              </td>
              <td className="px-4 py-3">
                <Link href={`/quotations/${q.id}`}>
                  <Button size="sm" variant="secondary" leftIcon={<Eye size={13} />}>
                    View
                  </Button>
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
