import { Quotation } from '@/types';

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'q1',
    clientName: 'Aryan Proteins Pvt. Ltd.',
    clientEmail: 'rajesh@aryanproteins.com',
    productName: 'Whey Protein Blend 2.0',
    productDescription: 'Premium whey protein concentrate blend with natural flavors and sweeteners for mass market retail.',
    ingredients: [
      { ingredientId: '5',  ingredientName: 'Whey Protein Concentrate', unit: 'KG', qtyUsed: 40, pricePerHundredKg: 890.00,  totalPrice: 356.00,  source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',             unit: 'KG', qtyUsed: 30, pricePerHundredKg: 65.00,   totalPrice: 19.50,   source: 'database' },
      { ingredientId: '1',  ingredientName: 'Sugar',                    unit: 'KG', qtyUsed: 20, pricePerHundredKg: 45.00,   totalPrice: 9.00,    source: 'database' },
      { ingredientId: '7',  ingredientName: 'Stevia Leaf Extract',      unit: 'KG', qtyUsed: 2,  pricePerHundredKg: 3400.00, totalPrice: 68.00,   source: 'database' },
      { ingredientId: 'ai1', ingredientName: 'Chocolate Flavor Blend', unit: 'KG', qtyUsed: 5,  pricePerHundredKg: 1250.00, totalPrice: 62.50,   source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 598.48,
    status: 'generated',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:05:00Z',
    pdfUrl: '/quotations/q1.pdf',
  },
  {
    id: 'q2',
    clientName: 'NutriMax Foods Pvt. Ltd.',
    clientEmail: 'priya@nutrimax.in',
    productName: 'Vitamin C Chewables',
    productDescription: 'Chewable vitamin C tablets with natural orange flavor, designed for children and adults.',
    ingredients: [
      { ingredientId: '6',  ingredientName: 'Vitamin C (Ascorbic Acid)', unit: 'KG', qtyUsed: 15, pricePerHundredKg: 1200.00, totalPrice: 180.00, source: 'database' },
      { ingredientId: '1',  ingredientName: 'Sugar',                     unit: 'KG', qtyUsed: 50, pricePerHundredKg: 45.00,   totalPrice: 22.50,  source: 'database' },
      { ingredientId: '7',  ingredientName: 'Stevia Leaf Extract',       unit: 'KG', qtyUsed: 1,  pricePerHundredKg: 3400.00, totalPrice: 34.00,  source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',              unit: 'KG', qtyUsed: 20, pricePerHundredKg: 65.00,   totalPrice: 13.00,  source: 'database' },
      { ingredientId: '15', ingredientName: 'Calcium Carbonate',         unit: 'KG', qtyUsed: 8,  pricePerHundredKg: 55.00,   totalPrice: 4.40,   source: 'database' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 292.18,
    status: 'sent',
    createdAt: '2024-05-28T14:00:00Z',
    updatedAt: '2024-05-29T09:00:00Z',
    pdfUrl: '/quotations/q2.pdf',
  },
  {
    id: 'q3',
    clientName: 'HealthFirst Supplements',
    clientEmail: 'anil@healthfirst.co.in',
    productName: 'Pre-Workout Energy Formula',
    productDescription: 'High-performance pre-workout powder with creatine, BCAAs and natural caffeine sources.',
    ingredients: [
      { ingredientId: '12', ingredientName: 'Creatine Monohydrate',  unit: 'KG', qtyUsed: 20, pricePerHundredKg: 480.00,  totalPrice: 96.00,  source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',          unit: 'KG', qtyUsed: 40, pricePerHundredKg: 65.00,   totalPrice: 26.00,  source: 'database' },
      { ingredientId: '13', ingredientName: 'Dextrose',              unit: 'KG', qtyUsed: 25, pricePerHundredKg: 38.00,   totalPrice: 9.50,   source: 'database' },
      { ingredientId: 'ai2', ingredientName: 'Green Tea Extract',    unit: 'KG', qtyUsed: 3,  pricePerHundredKg: 1800.00, totalPrice: 54.00,  source: 'ai-estimated' },
      { ingredientId: 'ai3', ingredientName: 'Beta-Alanine',         unit: 'KG', qtyUsed: 8,  pricePerHundredKg: 950.00,  totalPrice: 76.00,  source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 305.83,
    status: 'draft',
    createdAt: '2024-05-31T11:30:00Z',
    updatedAt: '2024-05-31T11:30:00Z',
  },
  {
    id: 'q4',
    clientName: 'Zenith Nutra Labs',
    clientEmail: 'sunita@zenithnutra.com',
    productName: 'Ashwagandha Stress Relief',
    productDescription: 'Premium ashwagandha root extract capsules with black pepper extract for enhanced bioavailability.',
    ingredients: [
      { ingredientId: '25', ingredientName: 'Ashwagandha Extract (5%)', unit: 'KG', qtyUsed: 20, pricePerHundredKg: 1480.00, totalPrice: 296.00, source: 'database' },
      { ingredientId: '9',  ingredientName: 'Magnesium Stearate',       unit: 'KG', qtyUsed: 5,  pricePerHundredKg: 280.00,  totalPrice: 14.00,  source: 'database' },
      { ingredientId: '14', ingredientName: 'Soy Lecithin',             unit: 'KG', qtyUsed: 8,  pricePerHundredKg: 195.00,  totalPrice: 15.60,  source: 'database' },
      { ingredientId: 'ai4', ingredientName: 'Black Pepper Extract (Piperine)', unit: 'KG', qtyUsed: 2, pricePerHundredKg: 2200.00, totalPrice: 44.00, source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 432.04,
    status: 'generated',
    createdAt: '2024-05-25T09:00:00Z',
    updatedAt: '2024-05-25T09:30:00Z',
    pdfUrl: '/quotations/q4.pdf',
  },
  {
    id: 'q5',
    clientName: 'BodyFortress India',
    clientEmail: 'vikram@bodyfortress.in',
    productName: 'Mass Gainer Supreme',
    productDescription: 'High-calorie mass gainer with whey protein, complex carbs and essential micronutrients.',
    ingredients: [
      { ingredientId: '5',  ingredientName: 'Whey Protein Concentrate', unit: 'KG', qtyUsed: 25, pricePerHundredKg: 890.00,  totalPrice: 222.50, source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',             unit: 'KG', qtyUsed: 50, pricePerHundredKg: 65.00,   totalPrice: 32.50,  source: 'database' },
      { ingredientId: '3',  ingredientName: 'Cocoa Powder',             unit: 'KG', qtyUsed: 10, pricePerHundredKg: 250.00,  totalPrice: 25.00,  source: 'database' },
      { ingredientId: '2',  ingredientName: 'Milk Powder',              unit: 'KG', qtyUsed: 15, pricePerHundredKg: 320.00,  totalPrice: 48.00,  source: 'database' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 383.88,
    status: 'archived',
    createdAt: '2024-04-15T10:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
    pdfUrl: '/quotations/q5.pdf',
  },
  {
    id: 'q6',
    clientName: 'Nature Wellness Co.',
    clientEmail: 'deepa@naturewellness.com',
    productName: 'Spirulina Green Blend',
    productDescription: 'Organic spirulina and chlorella blend with digestive enzymes for daily wellness.',
    ingredients: [
      { ingredientId: '16', ingredientName: 'Spirulina Powder',    unit: 'KG', qtyUsed: 30, pricePerHundredKg: 2850.00, totalPrice: 855.00,  source: 'database' },
      { ingredientId: '19', ingredientName: 'Inulin (Chicory Root)', unit: 'KG', qtyUsed: 15, pricePerHundredKg: 420.00, totalPrice: 63.00,  source: 'database' },
      { ingredientId: '9',  ingredientName: 'Magnesium Stearate',  unit: 'KG', qtyUsed: 5,  pricePerHundredKg: 280.00,  totalPrice: 14.00,  source: 'database' },
      { ingredientId: 'ai5', ingredientName: 'Chlorella Powder',   unit: 'KG', qtyUsed: 20, pricePerHundredKg: 3200.00, totalPrice: 640.00, source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 1808.80,
    status: 'sent',
    createdAt: '2024-05-20T13:00:00Z',
    updatedAt: '2024-05-21T08:00:00Z',
    pdfUrl: '/quotations/q6.pdf',
  },
  {
    id: 'q7',
    clientName: 'Fit India Supplements',
    clientEmail: 'meera@fitindia.co',
    productName: 'Gut Health Probiotic Mix',
    productDescription: 'Multi-strain probiotic blend with prebiotic inulin for optimal digestive health.',
    ingredients: [
      { ingredientId: '19', ingredientName: 'Inulin (Chicory Root)', unit: 'KG', qtyUsed: 30, pricePerHundredKg: 420.00,  totalPrice: 126.00, source: 'database' },
      { ingredientId: '24', ingredientName: 'Guar Gum',              unit: 'KG', qtyUsed: 10, pricePerHundredKg: 185.00,  totalPrice: 18.50,  source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',          unit: 'KG', qtyUsed: 20, pricePerHundredKg: 65.00,   totalPrice: 13.00,  source: 'database' },
      { ingredientId: 'ai6', ingredientName: 'Probiotic Blend (10B CFU)', unit: 'KG', qtyUsed: 5, pricePerHundredKg: 8500.00, totalPrice: 425.00, source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 673.73,
    status: 'draft',
    createdAt: '2024-06-01T08:00:00Z',
    updatedAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 'q8',
    clientName: 'Pure Harvest Nutraceuticals',
    clientEmail: 'sanjay@pureharvest.in',
    productName: 'Plant Protein Fusion',
    productDescription: 'Complete plant-based protein blend using pea protein and organic brown rice protein.',
    ingredients: [
      { ingredientId: '20', ingredientName: 'Pea Protein Isolate', unit: 'KG', qtyUsed: 50, pricePerHundredKg: 680.00,  totalPrice: 340.00, source: 'database' },
      { ingredientId: '8',  ingredientName: 'Maltodextrin',        unit: 'KG', qtyUsed: 25, pricePerHundredKg: 65.00,   totalPrice: 16.25,  source: 'database' },
      { ingredientId: '7',  ingredientName: 'Stevia Leaf Extract', unit: 'KG', qtyUsed: 2,  pricePerHundredKg: 3400.00, totalPrice: 68.00,  source: 'database' },
      { ingredientId: '21', ingredientName: 'Sunflower Lecithin', unit: 'KG', qtyUsed: 8,  pricePerHundredKg: 220.00,  totalPrice: 17.60,  source: 'database' },
      { ingredientId: 'ai7', ingredientName: 'Brown Rice Protein', unit: 'KG', qtyUsed: 30, pricePerHundredKg: 720.00,  totalPrice: 216.00, source: 'ai-estimated' },
    ],
    formulaBreakdown: '(Ingredient Cost × 1.15) + ₹5 Overhead',
    totalCost: 762.07,
    status: 'generated',
    createdAt: '2024-05-30T15:00:00Z',
    updatedAt: '2024-05-30T15:20:00Z',
    pdfUrl: '/quotations/q8.pdf',
  },
];
