import { Upload } from '@/types';

export const MOCK_UPLOADS: Upload[] = [
  {
    id: 'u1',
    fileName: 'ingredient_prices_june.xlsx',
    fileType: 'xlsx',
    uploadType: 'ingredient-file',
    status: 'completed',
    uploadedAt: '2024-06-01T09:15:00Z',
    processedRows: 25,
  },
  {
    id: 'u2',
    fileName: 'whey_blend_spec.pdf',
    fileType: 'pdf',
    uploadType: 'product-doc',
    status: 'completed',
    uploadedAt: '2024-05-30T14:22:00Z',
    linkedQuotationId: 'q1',
  },
  {
    id: 'u3',
    fileName: 'product_label_photo.jpg',
    fileType: 'jpg',
    uploadType: 'product-image',
    status: 'processing',
    uploadedAt: '2024-06-01T11:05:00Z',
    linkedQuotationId: 'q3',
  },
  {
    id: 'u4',
    fileName: 'raw_ingredient_list.txt',
    fileType: 'txt',
    uploadType: 'ingredient-file',
    status: 'failed',
    uploadedAt: '2024-05-28T16:40:00Z',
  },
  {
    id: 'u5',
    fileName: 'supplement_formula.docx',
    fileType: 'docx',
    uploadType: 'product-doc',
    status: 'completed',
    uploadedAt: '2024-05-25T10:30:00Z',
    processedRows: 8,
    linkedQuotationId: 'q2',
  },
  {
    id: 'u6',
    fileName: 'may_price_update.xlsx',
    fileType: 'xlsx',
    uploadType: 'ingredient-file',
    status: 'completed',
    uploadedAt: '2024-05-20T08:00:00Z',
    processedRows: 18,
  },
  {
    id: 'u7',
    fileName: 'product_image_v2.png',
    fileType: 'png',
    uploadType: 'product-image',
    status: 'processing',
    uploadedAt: '2024-06-01T12:55:00Z',
  },
];
