'use client';

import Link from 'next/link';
import type { ReportQuotationRecord } from '@/types';
import Button from '@/components/ui/Button';
import { downloadQuotationPdf } from '@/lib/api/quotations';
import { formatCurrency, formatDate } from '@/lib/utils';
import { Eye, Download, FileText } from 'lucide-react';
import toast from 'react-hot-toast';

function userLabel(row: ReportQuotationRecord): string {
  if (row.userName?.trim()) return row.userName.trim();
  return row.userEmail;
}

interface QuotationTableProps {
  quotations: ReportQuotationRecord[];
  loading?: boolean;
}

export default function QuotationTable({ quotations, loading = false }: QuotationTableProps) {
  const handleDownloadPdf = (quotationId: string, quotationNumber?: string) => {
    downloadQuotationPdf(quotationId, {
      filename: quotationNumber ? `${quotationNumber}.pdf` : undefined,
    });
    toast.success('PDF download started');
  };

  if (loading) {
    return (
      <p className="px-4 py-12 text-sm text-[#555555] text-center">Loading quotations…</p>
    );
  }

  if (quotations.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center">
        <div className="w-16 h-16 rounded-2xl bg-[#314f2d]/10 flex items-center justify-center mb-4">
          <FileText size={28} className="text-[#314f2d]" />
        </div>
        <p className="type-h3-18 text-[#0a0a0a]">No quotations found</p>
        <p className="type-small-body text-[#555555] mt-1">
          Adjust your search or create a new quotation.
        </p>
        <Link href="/quotations/new" className="mt-4">
          <Button>Create Quotation</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm min-w-[800px]">
        <thead>
          <tr className="border-b border-[#c3c3c3] bg-[#f2f6ef]">
            {[
              'Quotation',
              'Client',
              'Product',
              'Pack',
              'Total',
              'Generated by',
              'Date',
              'Actions',
            ].map((h) => (
              <th
                key={h}
                className="px-4 py-3 text-left text-[12px] font-semibold text-[#555555] uppercase tracking-wide whitespace-nowrap"
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {quotations.map((q, i) => (
            <tr
              key={q.id}
              className={[
                'group border-b border-l-4 border-l-transparent border-[#e8ece5] transition-all duration-100',
                i % 2 === 0 ? 'bg-white' : 'bg-[#f2f6ef]/60',
                'hover:bg-[#f2f6ef] hover:border-l-[#314f2d]',
              ].join(' ')}
            >
              <td className="px-4 py-3 font-mono text-xs text-[#314f2d] font-medium whitespace-nowrap">
                {q.quotationNumber}
              </td>
              <td className="px-4 py-3 font-medium text-[#0a0a0a] whitespace-nowrap">
                {q.clientName}
              </td>
              <td className="px-4 py-3 text-[#373737] max-w-[180px] truncate">
                {q.productName}
              </td>
              <td className="px-4 py-3 text-[#555555] tabular-nums whitespace-nowrap">
                {q.packWeightG}g
              </td>
              <td className="px-4 py-3 font-mono text-[#0a0a0a] whitespace-nowrap">
                {formatCurrency(q.totalPrice)}
              </td>
              <td className="px-4 py-3 text-[#373737]">
                <p className="font-medium text-[#0a0a0a] truncate max-w-[140px]">
                  {userLabel(q)}
                </p>
                {q.userName ? (
                  <p className="text-[11px] text-[#a3a29e] truncate max-w-[140px]">
                    {q.userEmail}
                  </p>
                ) : null}
              </td>
              <td className="px-4 py-3 text-[#555555] whitespace-nowrap">
                {formatDate(q.createdAt)}
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-1 flex-wrap">
                  <Link href={`/quotations/${q.id}`}>
                    <Button size="sm" variant="secondary" leftIcon={<Eye size={13} />}>
                      View
                    </Button>
                  </Link>
                  <button
                    type="button"
                    onClick={() => handleDownloadPdf(q.id, q.quotationNumber)}
                    className="p-1.5 rounded-lg text-[#555555] hover:text-[#314f2d] hover:bg-[#314f2d]/10 transition-colors cursor-pointer"
                    title="Download PDF"
                  >
                    <Download size={15} />
                  </button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
